version: '3'

tasks:
  init:
    requries:
      vars: 
        - ENV_FILE
        - DB_TYPE
        - DB_ALIAS
    dotenv:
      - /workspace/storage-env-files/{{ .ENV_FILE }}
    preconditions:
      - sh: |
          [[ -n "${S3_ENDPOINT_URL}" ]] && [[ -n "${S3_ACCESS_KEY_ID}" ]] && [[ -n "${S3_SECRET_ACCESS_KEY}" ]] && [[ -n "${S3_BUCKET}" ]]
        msg: "Required environment variables (S3_ENDPOINT_URL, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_BUCKET) are not set. Please check your .env file."
    vars: &common_vars
      S3_MC_ALIAS: 
        sh: echo {{ .ENV_FILE }} | sed 's/s3-//' | sed 's/.env//'
      S3_BUCKET: '${S3_BUCKET}'
      S3_SUBPATH: '{{ .DB_TYPE }}/{{ .DB_ALIAS }}'
    cmds: 
      - echo "Set alias '{{ .S3_MC_ALIAS }}' - '${S3_ENDPOINT_URL}'"
      - cmd: mc alias set {{ .S3_MC_ALIAS }} ${S3_ENDPOINT_URL} ${S3_ACCESS_KEY_ID} ${S3_SECRET_ACCESS_KEY}
      - echo "Alias '{{ .S3_MC_ALIAS }}' is ready!"

  upload:
    requires:
      vars: 
        - ENV_FILE
        - BACKUP_DIR
        - DB_TYPE
        - DB_ALIAS
    dotenv: 
      - /workspace/storage-env-files/{{ .ENV_FILE }}
    vars: *common_vars
    cmds:
      - mc cp --quiet --recursive {{ .BACKUP_DIR }} {{ .S3_MC_ALIAS }}/{{ .S3_BUCKET }}/{{ .S3_SUBPATH }}

  clean:
    requries:
      vars: 
        - ENV_FILE
        - DB_TYPE
        - DB_ALIAS
        - RETENTION_DAYS
    dotenv: 
      - /workspace/storage-env-files/{{ .ENV_FILE }}
    vars: *common_vars
    cmds: 
      - |
        for obj in $(mc find --older-than={{ .RETENTION_DAYS }}d {{ .S3_MC_ALIAS }}/{{ .S3_BUCKET }}/{{ .S3_SUBPATH }}/); do
          mc rm $obj
        done