name: Build and Push Packages

on:
  push:
    branches:
      - main
      - dev

jobs:
  init-setup:
    name: Initialize Setup
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c

      - name: Set Environment
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          else
            echo "env_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

  check-changed-images: 
    name: Check Images
    runs-on: ubuntu-latest
    needs: init-setup
    env: 
      changed_files: ${{ needs.init-setup.outputs.changed_files }}
    outputs:
      images: ${{ steps.get-changed-images.outputs.images }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get Changed Images
      id: get-changed-images
      run: |
        changed_images=$(echo ${changed_files} | tr ' ' '\n' | awk -F'/' '/^docker\// {print $2}' | sort -u)
        echo "images=$(echo ${changed_images} | tr -d '\n' | jq -Rsc 'split(" ")')" >> $GITHUB_OUTPUT
    - name: Debug Matrix
      run: |
        echo "Matrix: ${{ steps.get-changed-images.outputs.images }}"
  
  docker-image:
    name: Docker
    needs: 
      - init-setup
      - check-changed-images
    strategy:
      matrix: 
        image: ${{fromJson(needs.check-changed-images.outputs.images)}}
    if: needs.check-changed-images.outputs.images != '[]'
    uses: ./.github/workflows/_docker.yml
    with:
      image: '${{ matrix.image }}'
      ENV_NAME: '${{ needs.init-setup.outputs.env_name }}'
      DOCKER_HUB_USERNAME: kluvtad
      DOCKER_HUB_BASE_PATH: kluvtad
    secrets:
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  
  check-changed-charts:
    name: Check Helm Charts
    runs-on: ubuntu-latest
    needs: init-setup
    env: 
      changed_files: ${{ needs.init-setup.outputs.changed_files }}
    outputs:
      charts: ${{ steps.get-changed-charts.outputs.charts }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get Changed Helm Charts
        id: get-changed-charts
        run: |
          changed_charts=$(echo ${changed_files} | tr ' ' '\n' | awk -F'/' '/^helm\// {print $2}' | sort -u)
          echo "charts=$(echo ${changed_charts} | tr -d '\n' | jq -Rsc 'split(" ")')" >> $GITHUB_OUTPUT

      - name: Debug Matrix
        run: |
          echo "Matrix: ${{ steps.get-changed-charts.outputs.charts }}"

  helm-chart: 
    name: Helm Charts
    needs: check-changed-charts
    strategy:
      matrix: 
        chart: ${{fromJson(needs.check-changed-charts.outputs.charts)}}
    if: needs.check-changed-charts.outputs.charts != '[]'
    uses: ./.github/workflows/_helm.yml
    with:
      chart: '${{ matrix.chart }}'
      DOCKER_HUB_USERNAME: kluvtad
      DOCKER_HUB_BASE_PATH: kluvtad
    secrets:
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}